#!/bin/bash

# Get the database name from the command line argument
db_name=$1

# Use the mongo shell to connect to the MongoDB server and execute the count command
mongo --eval "db.${db_name}.school.count()"