#!/bin/bash

# Get the database name from the command line argument
db_name=$1

# Run the mongo command to list the documents
mongo $db_name --eval 'db.school.find({ name: { $regex: "^Holberton" } })'